### PR TITLE
dayfirst=False only if the value leads with 4-digit year

### PR DESCRIPTION
**Pull request by cat-bro**
If we can assume that we will always see DMY or YMD dates, this seems sensible.  Could have an argument for MDY?

### CODE REVIEW

**Comment by jarekwg** [comment]
@cat-bro What's wrong with the current implementation?

**Comment by cat-bro** [comment]
@jarekwg the current implementation will only pass dayfirst=True if the year has 4 digits.  DD/MM/YY will still be parsed with the month first.

**Comment by aidanlister** [comment]
We should be dayfirst=True (american dates not acceptable)

**Comment by aidanlister** [comment]
Oh, I guess this is a generic package. It should be a setting on the field.

**Comment by jarekwg** [comment]
Simply using `dayfirst=True` doesn't work as we'd like.
Our aim here is to support both DD/MM/YYYY and YYYY/MM/DD. That flag won't do that alone

@cat-bro if the year doesn't have 4 digits, XX/XX/XX, is ambiguous and the user deserves to get shot in the foot. BUT, that said, the default interpretation is YY/MM/DD, which is very computery. Regular people would generally write DD/MM/YYYY as you say. So sure, let's go with it.
I have a slight fear that some of our current users might be doing YY/MM/DD though, which'll turn things upside down for them. Meh.

I'll add tests and a `murican` flag then merge.

**Comment by cat-bro** [comment]
@jarekwg I don’t think the default behaviour of the dateutils parser is to interpret the year coming first out of xx/xx/xx.  It seems interpret it as either mm/dd/yy (dayfirst=False) or dd/mm/yy (dayfirst=True).

If any current users are putting in yy/mm/dd I’d be surprised if these

**Comment by cat-bro** [comment]
are being parsed correctly.  (Whoops accidentally closed this, using github on phone)

**Pull request merged**
